# Generated by Django 4.0.4 on 2022-06-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField()),
                ('serial_number', models.TextField()),
                ('date', models.DateField()),
                ('model_number', models.TextField()),
            ],
        ),
    ]
