# Generated by Django 4.0.4 on 2022-06-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='type',
            field=models.TextField(null=True),
        ),
    ]
