# Generated by Django 4.0.4 on 2022-06-06 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_home', '0002_productdetails_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetails',
            old_name='type',
            new_name='attachments',
        ),
        migrations.RenameField(
            model_name='productdetails',
            old_name='date',
            new_name='purchase_date',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='device_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='host_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='project',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
