# Generated by Django 4.0.4 on 2022-06-07 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_home', '0003_rename_type_productdetails_attachments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
