# Generated by Django 4.0.4 on 2022-06-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0004_alter_productdetails_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='sl_no',
            field=models.IntegerField(null=True),
        ),
    ]
